name: Code Quality

on:
    workflow_dispatch:
    pull_request:
    push:
        branches:
            - main

jobs:
    qodana:
        name: Qodana
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
            checks: write
        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.pull_request.head.sha }}
                  fetch-depth: 0
            - name: 'Qodana Scan'
              uses: JetBrains/qodana-action@v2024.1
              env:
                  QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
    phpstan:
        name: PHPStan
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.3
                  extensions: xdebug
                  coverage: xdebug

            - name: Get composer cache directory
              id: composer-cache
              run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

            - name: Cache composer dependencies
              uses: actions/cache@v4
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: "${{ runner.os }}-composer-${{ hashFiles('composer.json') }}"
                  restore-keys: |
                    "${{ runner.os }}-composer-${{ hashFiles('composer.json') }}-"
                    "${{ runner.os }}-composer-"

            - name: Install dependencies
              run: composer update --no-progress --no-suggest --prefer-dist --optimize-autoloader

            - name: Analyse PHP Code (PHPStan)
              run: composer run-script qa:phpstan
    csfixer:
        name: PHP CS Fixer
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.3
                  extensions: xdebug
                  coverage: xdebug

            - name: Get composer cache directory
              id: composer-cache
              run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

            - name: Cache composer dependencies
              uses: actions/cache@v4
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: "${{ runner.os }}-composer-${{ hashFiles('composer.json') }}"
                  restore-keys: |
                    "${{ runner.os }}-composer-${{ hashFiles('composer.json') }}-"
                    "${{ runner.os }}-composer-"

            - name: Install dependencies
              run: composer update --no-progress --no-suggest --prefer-dist --optimize-autoloader

            - name: Check Coding Style
              run: composer run-script cs:check
