name: Tests

on:
    workflow_dispatch:
    pull_request:
    push:
        branches:
            - main

permissions:
    contents: read

jobs:
    test:
        runs-on: ubuntu-latest

        name: Unit + Mutation

        steps:
            - uses: actions/checkout@v4

            - uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.3
                  extensions: xdebug
                  coverage: xdebug

            - name: Install dependencies
              run: composer update --no-interaction --no-scripts

            - name: Run unit tests
              run: composer run-script unit-tests

            - name: Run mutation tests
              run: composer run-script mutation-tests
